Revert "ARM: dts: msm: Add EEPROM node in camera sensor DTSi"
Fix:
ERROR: Input tree has errors, aborting (use -f to force output)
make[3]: *** [../arch/arm64/boot/dts/xiaomi/Makefile:13: arch/arm64/boot/dts/xiaomi/ginkgo-trinket-overlay.dtbo] Error 2
make[2]: *** [../scripts/Makefile.build:678: arch/arm64/boot/dts/xiaomi] Error 2
make[1]: *** [arch/arm64/Makefile:252: dtbs] Error 2
make[1]: *** Waiting for unfinished jobs....

This reverts commit 3b68c4e0f629d74cc410f4d29d1cc53d48cd4c82.

Signed-off-by: Muhammed Ali Simsek <malisimsek17@gmail.com>