msm: kgsl: Remove unused variable
../drivers/gpu/msm/kgsl_drawobj.c:398:19: error: unused variable 'i' [-Werror,-Wunused-variable]
        unsigned int id, i;
                         ^
1 error generated.

Change-Id: I3b1729bca3f48ac91a40ffdc01c0a84515422611